#!/usr/bin/env python
#za pokretanje bez puthon

from functions import *

def compress(inFilename,zipFilename):
    emptyFile(zipFilename)
    d = readFromFile(inFilename)
    dictionary = makeLZ77Dictionary(d)      #vraca listu slogova
    dictionary = makeDictionary(dictionary) #pravi dictionary od slogova
    dictionary = countWords(d,dictionary)   #broji koliko ima ponavljanja
    sortDictionary(dictionary)              #sortira na osnovu broja ponavljanja
    makeHuffmanCodes(dictionary)            #pravi huffman stablo za sortiran dictionary
    s = LZ77compress(d,dictionary)          #kompresovan kod
    writeDictionaryToFile(zipFilename,dictionary)       #upisivanje recnika u file
    writeCodeToFile(zipFilename,s)          #upisivanje koda u file
    
    return 0 

if __name__ == "__main__":
    if len(sys.argv) == 3:
        compress(sys.argv[1],sys.argv[2])
    elif len(sys.argv) == 4:
        if not os.path.exists(sys.argv[3]):
            os.makedirs(sys.argv[3])
        if sys.argv[1] != "-d":
            print("GRESKA")
        for file in os.listdir(sys.argv[2]):
            # print(sys.argv[2]+"/"+file)
            compress(sys.argv[2]+"/"+file,sys.argv[3]+"/"+file+".gzip")
    else:
        print("GRESKA")