#!/usr/bin/env python
from functions import *

def decompress(zipFilename,unzipFilename):
    emptyFile(unzipFilename)
    d = readContext(zipFilename)               #ucitavanje fajla
    dictionary = readDictionary(zipFilename)        #ucitava dictionary
    dictionary = decompressLZ77dictionary(dictionary)     #pravljenje recnika(kao strukture)
    s = decompressLZ77Codes(d,dictionary,dictionary[len(dictionary)-1].binCode,unzipFilename) #dekompresija glavnog dela
    writeCodeToFile(unzipFilename,s)            #ispis glavnog dela u file
    return 0


if __name__ == "__main__":
    decompress(sys.argv[1],sys.argv[2])
